### ISSUE TITLE
SSL mixed content 

### ISSUE THREAD

**Issue by WyRe** [MCServerStatus/MCServerStatus-WordPressWidget#5]
Excuse me publishing issues in here, but I think that problem could be of interest really unlike the previous one. I've got an SSL certificate installed in my webserver as you can see in [lentium](https://lentium.xyz) but I permanently have got the mixed content message, that message is caused by your plugin, concretely the part to fetch the skins from [cravatar.eu](https://cravatar.eu)

```
<?php if ($server['server']['server_platform'] == 'MINECRAFT') { ?>
      <?php echo '　<img src="https://cravatar.eu/helmhead/' . $player['name'] . '/' . $instance['avatar-size'] . '.png">'; ?>
<?php } else { ?>
	<?php  echo '　<img src="https://cravatar.eu/helmhead/steve/' . $instance['avatar-size'] . '.png">'; ?>
<?php } ?>
```

As you can see I've tried solving this by switching `http` for `https` in `online.phtml` but the mixed content persist, I think finally that's caused by the way in which [cravatar.eu](https://cravatar.eu) provides the avatar, I found much clearer use Firefox to inspect images loaded in the website. 

Of course people playing in MC server is needed, otherwise there will not be pics to  load and all ssl would be right.

Maybe we should contact with cravatar admins?

**Comment by WyRe** [comment]
Well, I've just found the issue, the problem is due to avatar size, when you choose a size less than 32 then [cravatar.eu](https://cravatar.eu) redirect you to 32 size in a way which does not includes their ssl cert. So I think could be convenient specify this in plugin docu, or maybe set a low limit to the avatar size to 32.

I let you the issue closing to decide if you wanna mark it as feature or something. Thank you again and sorry.

**Comment by GoneTone** [comment]
I will close this issue, This is cravatar.eu their setting problem.

**Comment by WyRe** [comment]
Ok, at the beginning I thought could be an issue with your code, when I did discover the cause I thought maybe you could be interested in it.

Thank you anyway and excuse me.

**Comment by GoneTone** [comment]
ok
